# Site settings
baseURL = "https://fabrizioulisse.it"
languageCode = "en-US"
title = "Fabrizio Ulisse"
theme = "hugo-split-theme"
disableKinds = ["section", "taxonomy", "RSS", "sitemap"]
disableHugoGeneratorInject = true

# Local preview mode
relativeURLs = true
uglyURLs = true

# Copyright
copyright = "&copy;2024 Fabrizio Ulisse"

# Whether you purchased the license from the author.
licensed = false

[markup.goldmark.renderer] 
  unsafe= true
  
[services]
  [services.googleAnalytics]
    # Enter your tracking code to enable Google Analytics
    ID = "G-Z3VHM8HR72"

[params]

  # Metadata for search engines and social sharing
  author = "Fabrizio Ulisse"
  description = "Humanizing tech complexities since cathod-ray tubes."
  shareImage = "images/fabrizio-ulisse.jpg"
  twitterHandle = "biccio"

  
  # Favicon
  favicon = "favicon.ico"

[params.custom.css]
  enable = true
  
  # Section - Visual
  [params.visual]
  
  
    # Image
    [params.visual.image]
      enable = true
      file = "images/fabrizio-ulisse.jpg"
      position = "center center"

    # Video
    [params.visual.video]
      enable = false
      mute = true
      file = "videos/background.mp4"
      # youtubeId = "dk9uNWPP7EA"

  # Links
  #
  # Links List #1
   [[params.links]]
    [params.links.list1]
      heading = "WRITINGS"

      [[params.links.list1.link]]
        text = "PrecisionDocs"
        url = "https://precisiondocs.tech"
        new_tab = true 

      [[params.links.list1.link]]
        text = "Ciclogravelista"
        url = "https://ciclogravelista.com"
        new_tab = true 

      [[params.links.list1.link]]
        text = "Uno e Sessantacinque"
        url = "https://unoesessantacinque.substack.com"
        new_tab = true 

# Links List #2
   [[params.links]]
    [params.links.list1]
      heading = "PROFESSIONAL"

      [[params.links.list1.link]]
        text = "Github"
        url = "https://github.com/biccio"
        new_tab = true 

      [[params.links.list1.link]]
        text = "Linkedin"
        url = "https://linkedin.com/in/ulisse"
        new_tab = true 



# Links List #3
   [[params.links]]
    [params.links.list1]
      heading = "SOCIAL"

      [[params.links.list1.link]]
        text = "Instagram"
        url = "https://instagram.com/biccio"
        new_tab = true 

      [[params.links.list1.link]]
        text = "Mastodon"
        url = "https://hachyderm.io/@biccio"
        new_tab = true 

      [[params.links.list1.link]]
        text = "BlueSky"
        url = "https://bsky.app/profile/biccio.bsky.social"
        new_tab = true 

      [[params.links.list1.link]]
        text = "Spotify"
        url = "https://open.spotify.com/user/1167647796"
        new_tab = true 

  # The original template is released under the Creative Commons Attribution 3.0 License.
  # Please keep the original attribution link when using for your own project.
  # If you'd like to use the template without the attribution, you can check out
  # the license option via the template author's website: https://onepagelove.com/split

[server]
[[server.headers]]
    for = '/**'
    [server.headers.values]
      Content-Security-Policy = "default-src 'self'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' https://dummyimage.com"
      Referrer-Policy = 'strict-origin-when-cross-origin'
      X-Content-Type-Options = 'nosniff'
      X-Frame-Options = 'DENY'
      X-XSS-Protection = '1; mode=block'
