# Site settings
baseURL = "https://fabrizioulisse.it"
languageCode = "en-US"
title = "Fabrizio Ulisse"
theme = "hugo-split-theme"
disableKinds = ["section", "taxonomy", "RSS", "sitemap"]
disableHugoGeneratorInject = true

# Local preview mode
relativeURLs = true
uglyURLs = true

# Copyright
copyright = "&copy;2024 Your Name"

# Whether you purchased the license from the author.
licensed = false

[services]
  [services.googleAnalytics]
    # Enter your tracking code to enable Google Analytics
    ID = ""

[params]

  # Metadata for search engines and social sharing
  author = "Fabrizio Ulisse"
  description = "Tech writer, gravel bike rider, father. Simplyfing digital complexities since cathode-ray tubes."
  shareImage = "images/fabrizio-ulisse.jpg"
  twitterHandle = "biccio"

  
  # Favicon
  favicon = "favicon.ico"

[params.custom.css]
  enable = true
  
  # Section - Visual
  [params.visual]
  
  
    # Image
    [params.visual.image]
      enable = true
      file = "images/fabrizio-ulisse.jpg"
      position = "center center"

    # Video
    [params.visual.video]
      enable = false
      mute = true
      file = "videos/background.mp4"
      # youtubeId = "dk9uNWPP7EA"

  # Links
  #
  # Links List #1
  [[params.links]]
    [params.links.list1]
      heading = ""

      [[params.links.list1.link]]
        text = "→ PRECISIONDOCS"
        url = "https://precisiondocs.tech"
        new_tab = true # new tab

      [[params.links.list1.link]]
        text = "→ UNO E SESSANTACINQUE"
        url = "https://unoesessantacinque.substack.com"
        new_tab = false # Default, open at same tab

      [[params.links.list1.link]]
        text = "→ CICLOGRAVELISTA"
        url = "https://ciclogravelista.com"

      [[params.links.list1.link]]
        text = "→ GITHUB"
        url = "https://github.com/biccio"

      [[params.links.list1.link]]
        text = "→ LINKEDIN"
        url = "https://linkedin.com/in/fabrizioulisse"
  # The original template is released under the Creative Commons Attribution 3.0 License.
  # Please keep the original attribution link when using for your own project.
  # If you'd like to use the template without the attribution, you can check out
  # the license option via the template author's website: https://onepagelove.com/split

[server]
[[server.headers]]
    for = '/**'
    [server.headers.values]
      Content-Security-Policy = "default-src 'self'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' https://dummyimage.com"
      Referrer-Policy = 'strict-origin-when-cross-origin'
      X-Content-Type-Options = 'nosniff'
      X-Frame-Options = 'DENY'
      X-XSS-Protection = '1; mode=block'
